# Generated by Django 4.1.2 on 2023-01-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("token_api", "0003_register_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_kyc_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kyc_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("kyc_img_name", models.CharField(max_length=200)),
                (
                    "kyc_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="token_api.register_user",
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
