# Generated by Django 4.1.2 on 2023-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("token_api", "0004_user_kyc_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_kyc_info",
            name="kyc_img_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
