# Generated by Django 4.1.2 on 2022-12-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practice_api2", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="model_movies",),
    ]
