# Generated by Django 4.1.2 on 2022-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice_api2", "0002_delete_model_movies"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_movies2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie", models.CharField(max_length=100)),
                ("character", models.CharField(max_length=100)),
            ],
        ),
    ]
